## This rule redirects to an external API
[[redirects]]
  from = "/sgov-server/*"
  to = "https://kbss.felk.cvut.cz/sgov-server/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}